runtime: php
env: flex

runtime_config:
  document_root: ./index.html


handlers:

# Handle the main page by serving the index page.
# Note the $ to specify the end of the path, since app.yaml does prefix matching.
- url: /
  static_files: index.html
  upload: index.html